---
git_resources:
- name: api
  uri: ((api.uri))
  branch: ((api.branch))
  private_key: ((api.private_key))
  paths:
    - api/**
- name: ci
  uri: ((ci.uri))
  branch: ((ci.branch))
  private_key: ((ci.private_key))
  paths:
    - ci/**

environments:
- name: dev
  artifact: snapshot
  version: build-version
  previous: build-and-publish
  trigger: true
- name: acceptance
  artifact: snapshot
  version: build-version
  previous: deploy-to-dev
  version_params:
    bump: patch
- name: staging
  artifact: release
  version: rc-version
  previous: nominate-for-release
- name: prod
  artifact: release
  version: rc-version
  previous: prepare-for-prod

builds:
- name: build
  job: build-and-publish
  artifact: snapshot
  version:
    in: version
    trigger: true
    params:
      pre: build
    out: build-version
- name: rc
  job: nominate-for-release
  artifact: release
  previous: deploy-to-acceptance
  trigger: true
  version:
    in: rc-version
    params:
      pre: rc
    out: rc-version
- name: release
  job: prepare-for-prod
  artifact: release
  previous: deploy-to-staging
  version:
    in: rc-version
    params:
      bump: final
    out: version


# Mostly static
artifacts:
- release
- snapshot

version_types:
- patch
- minor
- major
